[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'This is a multi-service project. Please deploy individual services from backend/ and storefront/ directories.'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production" 