[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn migrate && yarn start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production" 